Move font loading to background thread
Automattic/portkey-android pull request #639
Opened 2021-02-12 01:46 UTC by aforcier

Should fix https://github.com/wordpress-mobile/WordPress-Android/issues/13693.

Stories relies on several downloadable fonts. It seems the problem was that on slow connections (or perhaps if the Google font server was unavailable to the user for any reason), obtaining the fonts can take a while, and we were making the request on the UI thread - leading to an ANR.

`ResourcesCompat#getFont()` turns out to support asynchronous font requests for this reason. However, asynchronously downloading when the text editor launches is too late; we'd always be using the fallback fonts instead of the custom fonts on first run of the story feature, which we don't want.

My solution is to cue the font loading ahead of time, when the story creator is started up. This will trigger the font download (if they're not already downloaded - otherwise `ResourcesCompat` will serve up the cached local font reference) and save the resolved font reference in the new `FontRequester`. Later requests to display the font are handled by `FontRequester`, which will serve up whatever it got from `ResourcesCompat` (or the fallback font in case of errors or if the callback hasn't been called yet).

Note: `FontRequester` behaves like a singleton - it should really be a dagger module and injected into `ComposeLoopFrameActivity` and `TextStyleGroupManager`, but that was starting to become too big a diversion. I think this is okay for now and we should plan a bigger dagger refactor for this and other areas where we need it (see #357 also).

### To test

Try things out on an emulator wiped clean (so any locally saved fonts are removed). If you filter for `font` in the log and run the app, you should see this when the creator is launched:

(The `V` logs from `com.automattic.loop` are temporary logging I added for testing and not included in the PR - the first set inside `registerFont()`, the second set in `onFontRetrieved()`).

```
com.automattic.loop V/FontRequester: Registering font: 2131296257
com.automattic.loop V/FontRequester: Registering font: 2131296256
com.automattic.loop V/FontRequester: Registering font: 2131296258
com.automattic.loop V/FontRequester: Registering font: 2131296259
com.automattic.loop V/FontRequester: Registering font: 2131296261
com.automattic.loop V/FontRequester: Registering font: 2131296260
com.google.android.gms I/FontsContentProvider: Received query name=Nunito&weight=700, URI content://com.google.android.gms.fonts
com.google.android.gms I/FontsContentProvider: Query [name=Nunito&weight=700] resolved to {Nunito, wdth 100.0, wght 700, ital 0.0, bestEffort false}
com.google.android.gms I/FontsContentProvider: Fetch {Nunito, wdth 100.0, wght 700, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null}
com.google.android.gms I/FontsContentProvider: Pulling font file for id = 6, cache size = 5
com.google.android.gms I/FontsContentProvider: Received query Libre Baskerville, URI content://com.google.android.gms.fonts
com.google.android.gms I/FontsContentProvider: Query [Libre Baskerville] resolved to {Libre Baskerville, wdth 100.0, wght 400, ital 0.0, bestEffort false}
com.google.android.gms I/FontsContentProvider: Fetch {Libre Baskerville, wdth 100.0, wght 400, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null}
com.google.android.gms I/FontsContentProvider: Pulling font file for id = 7, cache size = 6
com.google.android.gms I/FontsContentProvider: Received query Pacifico, URI content://com.google.android.gms.fonts
com.google.android.gms I/FontsContentProvider: Query [Pacifico] resolved to {Pacifico, wdth 100.0, wght 400, ital 0.0, bestEffort false}
com.google.android.gms I/FontsContentProvider: Fetch {Pacifico, wdth 100.0, wght 400, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null}
com.google.android.gms I/FontsContentProvider: Pulling font file for id = 8, cache size = 7
com.google.android.gms I/FontsContentProvider: Received query name=Space Mono&weight=700, URI content://com.google.android.gms.fonts
com.google.android.gms I/FontsContentProvider: Query [name=Space Mono&weight=700] resolved to {Space Mono, wdth 100.0, wght 700, ital 0.0, bestEffort false}
com.google.android.gms I/FontsContentProvider: Fetch {Space Mono, wdth 100.0, wght 700, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null}
com.google.android.gms I/FontsContentProvider: Pulling font file for id = 9, cache size = 6
com.google.android.gms I/FontsContentProvider: Received query Shrikhand, URI content://com.google.android.gms.fonts
com.google.android.gms I/FontsContentProvider: Query [Shrikhand] resolved to {Shrikhand, wdth 100.0, wght 400, ital 0.0, bestEffort false}
com.google.android.gms I/FontsContentProvider: Fetch {Shrikhand, wdth 100.0, wght 400, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null}
com.google.android.gms I/FontsContentProvider: Pulling font file for id = 10, cache size = 7
com.automattic.loop V/FontRequester: Font retrieved from ResourcesCompat: 2131296258
com.automattic.loop V/FontRequester: Font retrieved from ResourcesCompat: 2131296257
com.automattic.loop V/FontRequester: Font retrieved from ResourcesCompat: 2131296256
com.automattic.loop V/FontRequester: Font retrieved from ResourcesCompat: 2131296259
com.automattic.loop V/FontRequester: Font retrieved from ResourcesCompat: 2131296261
com.automattic.loop V/FontRequester: Font retrieved from ResourcesCompat: 2131296260
```

If after that you open the text editor, you should see the fonts already preloaded, and no new requests to `FontsContentProvider` in the log.

2021-02-12 19:28 UTC, mzorz commented on stories/src/main/java/com/wordpress/stories/compose/text/FontRequester.kt
> +        fontMap[fontRes] = fallback
nice touch here acting preemptively ✅

2021-02-12 20:14 UTC, mzorz commented on stories/src/main/java/com/wordpress/stories/compose/text/FontRequester.kt
> +            Log.e(TAG, "Font ${context.resources.getResourceEntryName(fontRes)} not found")
This is a nitpick that ended up being an interesting internal check  - giving a heads up so you can decide whether this makes sense to consider or not 👍:

I was going to ask whether it is possible to get an Exception from an async call directly 😅  but then realized looking into ResourcesCompat's  source code that `getFont` calls `loadFont()` internally and it only throws this when no callback is passed
```
        if (typeface == null && fontCallback == null) {
            throw new NotFoundException("Font resource ID #0x"
                    + Integer.toHexString(id) + " could not be retrieved.");
        }
```
Even `getFont()` has a [precheck](https://android.googlesource.com/platform/frameworks/support/+/HEAD/core/core/src/main/java/androidx/core/content/res/ResourcesCompat.java#358) that the callback shouldn't be null or it throws an NPE:

```
Preconditions.checkNotNull(fontCallback);
```

`Preconditions.checkNotNull` will throw a NPE if the passed parameter is null - I wondered if we should also catch  NPE here in this try/catch clause, but I guess in our case it will never be thrown because we always pass a callback which is also an `object` method so it is guaranteed to live with the Application process.

So yes, all this to say, we can probably get rid of the try/catch clause and only declare the `throws ...` at the method declaration level and let the user of the library decide. Unless we want to encapsulate this behavior and just have the FontRequester resolve everything, which is also nice.

2021-02-12 20:18 UTC, mzorz commented on stories/src/main/java/com/wordpress/stories/compose/text/FontRequester.kt
> +    val fontMap = mutableMapOf<Int, Typeface>()
I've seen Kotlin provides a `[LinkedHashMap](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html)` as the implementation of `mutableMapOf`.
A LinkedHashMap is not thread safe, so I wondered what would happen in the (possibly very rare) case where several fonts are retrieved and then their async callbacks decide to assign values to it (write) at the same time.

Generally I'd think there wouldn't be a problem given all keys in the map are guaranteed to be different, but it really depends on the implementation (maybe registering a new key makes values to shift in the underlying data structure, which would then potentially be problematic given the insertion method is not synchronized).

So in order to avoid this, this would need to be externally synchronized, one way is to use `Collections.synchronizedMap`  wdyt?

```suggestion
    val fontMap = Collections.synchronizedMap(mutableMapOf<Int, Typeface>())
```

2021-02-12 20:26 UTC, mzorz requested changes
Nice work @aforcier ! 🙌 

I tested and verified it works, on API 22 and API29, with airplane mode ON first and OFF afterwards to verify it loads.

I love how code looks simple to understand and is well documented - left a couple of comments, one of them I think would be nice to address before merging (re: the thread safety of the `fontMap`). 

Feel free to merge afterwards 👍

2021-02-13 01:59 UTC, aforcier commented on stories/src/main/java/com/wordpress/stories/compose/text/FontRequester.kt
> +            Log.e(TAG, "Font ${context.resources.getResourceEntryName(fontRes)} not found")
> Preconditions.checkNotNull will throw a NPE if the passed parameter is null - I wondered if we should also catch NPE here in this try/catch clause, but I guess in our case it will never be thrown because we always pass a callback which is also an object method so it is guaranteed to live with the Application process.

Yes agreed. I think it makes sense to continue to catch `NotFoundException` since it's explicitly thrown by `getFont` (and even though looking into the internals reveals that it shouldn't get thrown in our case, the internals could always change in a future update).

> Unless we want to encapsulate this behavior and just have the FontRequester resolve everything, which is also nice.

I think we can encapsulate the behavior - in general `FontRequester` is supposed to give you back the fallback font if anything goes wrong, I think eating the potential `NotFoundException` and using the fallback falls within what you'd expect the object to do.

2021-02-13 02:40 UTC, aforcier commented on stories/src/main/java/com/wordpress/stories/compose/text/FontRequester.kt
> +    val fontMap = mutableMapOf<Int, Typeface>()
Good point @mzorz , let's be safe 👍 Made the change in 5e79486 (the `fontMap` type needs an explicit cast for null safety reasons, otherwise it generates a warning).

2021-02-13 02:43 UTC, merged

2021-02-13 02:49 UTC, aforcier commented
Thanks @mzorz! Updated and merged per your comment. WPAndroid PR updating the hash is here: https://github.com/wordpress-mobile/WordPress-Android/pull/14065