Android 13 migration update compile sdk version to 33
Automattic/portkey-android pull request #728
Opened 2023-03-15 01:42 UTC by ravishanker

Updates compileSdkVersion from 31 to 33 (Android 13)

Internal project thread: pbArwn-5IN-p2

Fixes: [#18096](https://github.com/wordpress-mobile/WordPress-Android/issues/18096)

To test

- Checkout this branch
- Use this branch through WP (uncomment localStoriesAndroidPath in local-builds.gradle)
- Try out adding a Story post (FAB > Story post) with an image and/or video
- Ensure, no issues or crashes

2023-03-15 02:03 UTC, ravishanker commented
@ParaskP7 - Looks like stories-android still has CircleCI checks!

2023-03-15 15:23 UTC, ParaskP7 commented
👋 @ravishanker !

> @ParaskP7 - Looks like stories-android still has CircleCI checks!

You're right, it looks that the `CircleCI` to `Buildkite` migration hasn't been completed for this repo, just like it happened for the rest of them, and to be honest, I am not sure why... 🤔 Cc @oguzkocer

2023-03-15 18:27 UTC, oguzkocer commented
@jkmassel was working on these migrations, but we have a lot of repos, so it's most likely an oversight. If this is a blocker, I can try and handle this migration this week.

2023-03-15 22:13 UTC, ravishanker commented
> @jkmassel was working on these migrations, but we have a lot of repos, so it's most likely an oversight. If this is a blocker, I can try and handle this migration this week.

@oguzkocer Yes, please.  Thank you

2023-03-16 21:44 UTC, oguzkocer commented
> @oguzkocer Yes, please. Thank you

I've moved the lint & unit test tasks to Buildkite in #729. I'm waiting some feedback from the App Infrastructure Team about the installable build, but worst case scenario, we can merge #729 tomorrow and open a separate PR for the installable build.

@ravishanker If you can let me know the urgency of this PR, I can take the appropriate action. Thank you!

2023-03-17 11:50 UTC, irfano commented
> > @oguzkocer Yes, please. Thank you
> 
> I've moved the lint & unit test tasks to Buildkite in #729. I'm waiting some feedback from the App Infrastructure Team about the installable build, but worst case scenario, we can merge #729 tomorrow and open a separate PR for the installable build.
> 
> @ravishanker If you can let me know the urgency of this PR, I can take the appropriate action. Thank you!

Thank you for handling this, @oguzkocer! This is not too urgent and does not need to be merged this week. It can be merged in our next sprint.

2023-03-17 18:56 UTC, oguzkocer commented
Thanks @irfano! https://github.com/Automattic/stories-android/pull/729 is now ready for review, so it should be merged early next week 🤞

2023-03-19 21:48 UTC, oguzkocer commented
@ravishanker @irfano https://github.com/Automattic/stories-android/pull/729 is merged. You can merge `trunk` into this branch which should trigger Buildkite to run the jobs instead of CircleCI. Please let me know if you have any issues!

2023-03-20 20:22 UTC, irfano requested changes
I have requested a minor change. Once it is resolved, we will be ready to merge.

2023-03-20 20:22 UTC, irfano commented on build.gradle
> -        jcenter()
Removing jcenter causes failure of fetching some libraries for the example app. (for example: `com.facebook.flipper:0.50.0`)
I think we can revert this change to avoid resolving more errors on the example app.

2023-03-21 05:27 UTC, ravishanker commented on build.gradle
> -        jcenter()
Looks like[ flipper is available from 0.54.0 on mavenCentral](https://mvnrepository.com/artifact/com.facebook.flipper/flipper).  Updated the flipper version to what we have on version catalog.  All failures have disappeared now.

2023-03-21 12:51 UTC, irfano requested changes
I tested the Loop demo app but it isn't going to the next screen after requesting permission. I think the permission code needs to be updated.

2023-03-21 12:51 UTC, irfano commented on build.gradle
> -        jcenter()
It's fixed! 👍🏻

2023-03-22 03:15 UTC, ravishanker commented
> I tested the Loop demo app but it isn't going to the next screen after requesting permission. I think the permission code needs to be updated.

It has READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE .  Better handle that separately as part of [media permissions task](https://github.com/wordpress-mobile/WordPress-Android/issues/17715)

2023-03-23 20:34 UTC, irfano approved these changes
@ravishanker 👋🏻 
`READ_EXTERNAL_STORAGE` permission still exists in `photoeditor` package. But I'm not sure if it's required or not. If you like to investigate it to ensure it won't break anything, you can do it before merging. Otherwise feel free to merge it. I'm approving the PR. It works on WPAndroid app and also on the example.

2023-03-24 03:09 UTC, merged